version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/TLServer.crt:/etc/nginx/ssl/TLServer.crt:ro
      - ./nginx/TLServer.key:/etc/nginx/ssl/TLServer.key:ro
    depends_on:
      - web

  web:
    build: .
    expose:
      - "61117"
    command: waitress-serve --listen=0.0.0.0:61117 proxy:app
